config/routes.rb
Api::Application.routes.draw do
  resources :uploaded_files

  wash_out :soap
  resources :rest

end

app/models/record.rb
class Record < WashOut::Type
  attr_accessor :id, :name

  type_name = 'record'
  map :record => {
        :name => :string,
        :id  => :int
      }
end

app/models/uploaded_file.rb
class UploadedFile
  include Mongoid::Document

  mount_uploader :avatar, AvatarUploader

  validate :file_ext

  def file_ext
    unless avatar.file.extension.downcase == 'csv'
      errors.add(:file_type, "::You cannot upload a file other then CSV file")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rest_controller.rb
require 'csv'
class RestController < ApplicationController
  http_basic_authenticate_with name: "a", password: "a"#, except: :index

  def index
    file_name = params["file"]
    file_name = file_name ||= 'data.csv'
    file_path = Rails.root.join('public', 'csv', file_name)

    data = CSV.open(file_path, headers: true, header_converters: :symbol, converters: :all).to_a.map(&:to_hash).to_json

    render json: data
  end

  private

  def permitted_params
    params.require(:user).permit(:id, :name)
  end

  def doc_not_found
    render json: { errors: ['Document Not Found'] }, status: :not_found
  end
end

app/controllers/rumbas_controller.rb
  # app/controllers/rumbas_controller.rb
class RumbasController < ApplicationController
  soap_service namespace: 'urn:WashOut', wsse_username: "username", wsse_password: "password"

  # Simple case
  soap_action "integer_to_string",
              :args   => :integer,
              :return => :string
  def integer_to_string
    render :soap => params[:value].to_s
  end

  soap_action "concat",
              :args   => { :a => :string, :b => :string },
              :return => :string
  def concat
    render :soap => (params[:a] + params[:b])
  end

  # Complex structures
  soap_action "AddCircle",
              :args   => { :circle => { :center => { :x => :integer,
                                                     :y => :integer },
                                        :radius => :double } },
              :return => nil, # [] for wash_out below 0.3.0
              :to     => :add_circle
  def add_circle
    circle = params[:circle]

    raise SOAPError, "radius is too small" if circle[:radius] < 3.0

    Circle.new(circle[:center][:x], circle[:center][:y], circle[:radius])

    render :soap => nil
  end

  # Arrays
  soap_action "integers_to_boolean",
              :args => { :data => [:integer] },
              :return => [:boolean]
  def integers_to_boolean
    render :soap => params[:data].map{|x| x ? 1 : 0}
  end

  # With a customised input tag name, in case params are wrapped;
  # e.g. for a request to the 'IntegersToBoolean' action:
  #   <soapenv:Envelope>
  #     <soapenv:Body>
  #       <MyRequest>  <!-- not <IntegersToBoolean> -->
  #         <Data>...</Data>
  #       </MyRequest>
  #     </soapenv:Body>
  #   </soapenv:Envelope>
  soap_action "integers_to_boolean",
              :args => { :my_request => { :data => [:integer] } },
              :as => 'MyRequest',
              :return => [:boolean]

  # You can use all Rails features like filtering, too. A SOAP controller
  # is just like a normal controller with a special routing.
  before_filter :dump_parameters
  def dump_parameters
    Rails.logger.debug params.inspect
  end
end

app/controllers/soap_controller.rb
  # app/controllers/soaps_controller.rb
class SoapController < ApplicationController
  soap_service namespace: 'urn:WashOut'#, wsse_username: "a", wsse_password: "a"


  # Simple case
  soap_action "get_data",
              :args   => :integer,
              :return => Record
  def get_data
    record = Record.new
    record.id = params[:value]
    record.name = 'name'
    render :soap => record
  end

  # Simple case
  soap_action "integer_to_string",
              :args   => :integer,
              :return => :string
  def integer_to_string
    render :soap => params[:value].to_s
  end

  soap_action "concat",
              :args   => { :a => :string, :b => :string },
              :return => :string
  def concat
    render :soap => (params[:a] + params[:b])
  end
=begin

  # Complex structures
  soap_action "AddCircle",
              :args   => { :circle => { :center => { :x => :integer,
                                                     :y => :integer },
                                        :radius => :double } },
              :return => nil, # [] for wash_out below 0.3.0
              :to     => :add_circle
  def add_circle
    circle = params[:circle]

    raise SOAPError, "radius is too small" if circle[:radius] < 3.0

    Circle.new(circle[:center][:x], circle[:center][:y], circle[:radius])

    render :soap => nil
  end

  # Arrays
  soap_action "integers_to_boolean",
              :args => { :data => [:integer] },
              :return => [:boolean]
  def integers_to_boolean
    render :soap => params[:data].map{|x| x ? 1 : 0}
  end

  # With a customised input tag name, in case params are wrapped;
  # e.g. for a request to the 'IntegersToBoolean' action:
  #   <soapenv:Envelope>
  #     <soapenv:Body>
  #       <MyRequest>  <!-- not <IntegersToBoolean> -->
  #         <Data>...</Data>
  #       </MyRequest>
  #     </soapenv:Body>
  #   </soapenv:Envelope>
  soap_action "integers_to_boolean",
              :args => { :my_request => { :data => [:integer] } },
              :as => 'MyRequest',
              :return => [:boolean]

  # You can use all Rails features like filtering, too. A SOAP controller
  # is just like a normal controller with a special routing.
=end

  before_filter :dump_parameters
  def dump_parameters
    Rails.logger.debug params.inspect
  end
end

app/controllers/uploaded_files_controller.rb
class UploadedFilesController < ApplicationController
  before_action :set_uploaded_file, only: [:show, :edit, :update, :destroy]

  # GET /uploaded_files
  # GET /uploaded_files.json
  def index
    @uploaded_files = UploadedFile.all
  end

  # GET /uploaded_files/1
  # GET /uploaded_files/1.json
  def show
  end

  # GET /uploaded_files/new
  def new
    @uploaded_file = UploadedFile.new
  end

  # GET /uploaded_files/1/edit
  def edit
  end

  # POST /uploaded_files
  # POST /uploaded_files.json
  def create
    @uploaded_file = UploadedFile.new(uploaded_file_params)

    respond_to do |format|
      if @uploaded_file.save
        format.html { redirect_to @uploaded_file, notice: 'Uploaded file was successfully created.' }
        format.json { render action: 'show', status: :created, location: @uploaded_file }
      else
        format.html { render action: 'new' }
        format.json { render json: @uploaded_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uploaded_files/1
  # PATCH/PUT /uploaded_files/1.json
  def update
    respond_to do |format|
      if @uploaded_file.update(uploaded_file_params)
        format.html { redirect_to @uploaded_file, notice: 'Uploaded file was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @uploaded_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploaded_files/1
  # DELETE /uploaded_files/1.json
  def destroy
    @uploaded_file.destroy
    respond_to do |format|
      format.html { redirect_to uploaded_files_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_uploaded_file
      @uploaded_file = UploadedFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def uploaded_file_params
      params.require(:uploaded_file).permit(:avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploaded_files_helper.rb
module UploadedFilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Api</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/uploaded_files/_form.html.erb
<%= form_for(@uploaded_file) do |f| %>
  <% if @uploaded_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@uploaded_file.errors.count, "error") %> prohibited this uploaded_file from being saved:</h2>

      <ul>
      <% @uploaded_file.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.file_field :avatar %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/uploaded_files/edit.html.erb
<h1>Editing uploaded_file</h1>

<%= render 'form' %>

<%= link_to 'Show', @uploaded_file %> |
<%= link_to 'Back', uploaded_files_path %>

app/views/uploaded_files/index.html.erb
<h1>Listing uploaded_files</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @uploaded_files.each do |uploaded_file| %>
      <tr>
        <td><%= link_to uploaded_file.avatar.file.filename, uploaded_file.avatar.url %></td>
        <td><%= link_to 'Show', uploaded_file %></td>
        <td><%= link_to 'Edit', edit_uploaded_file_path(uploaded_file) %></td>
        <td><%= link_to 'Destroy', uploaded_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Uploaded file', new_uploaded_file_path %>

app/views/uploaded_files/new.html.erb
<h1>New uploaded_file</h1>

<%= render 'form' %>

<%= link_to 'Back', uploaded_files_path %>

app/views/uploaded_files/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to @uploaded_file.avatar.file.filename, @uploaded_file.avatar.url %> |
<%= link_to 'Edit', edit_uploaded_file_path(@uploaded_file) %> |
<%= link_to 'Back', uploaded_files_path %>